// ============================================================
//  AI Product Team — Dashboard Server
// ============================================================
'use strict';

const express = require('express');
const fs      = require('fs');
const path    = require('path');
const { execSync } = require('child_process');
const { parse } = require('jsonc-parser');

const app  = express();
const PORT = process.env.PORT || 3030;

const TEAM_DIR    = path.join(__dirname, '..');
const SHARED_DIR  = path.join(TEAM_DIR,   'shared');
const LOGS_DIR    = path.join(SHARED_DIR, 'logs');
const INBOX_DIR   = path.join(SHARED_DIR, 'inbox');
const CONFIG_FILE = path.join(TEAM_DIR,   'config.sh');
const PATHS_FILE  = path.join(SHARED_DIR, 'paths.json');
const TASKS_FILE   = path.join(SHARED_DIR, 'tasks.json');
const WORKFLOW_DIR = path.join(SHARED_DIR, 'workflow');

// ── Paths config (runtime, mutable) ─────────────────────────

const DEFAULT_PATHS = {
  workspace:   path.join(SHARED_DIR, 'project', 'code'),
  projectRoot: path.join(SHARED_DIR, 'project'),
};

function loadPaths() {
  try {
    const raw = JSON.parse(fs.readFileSync(PATHS_FILE, 'utf8'));
    return {
      workspace:   raw.workspace   || DEFAULT_PATHS.workspace,
      projectRoot: raw.projectRoot || DEFAULT_PATHS.projectRoot,
    };
  } catch {
    // Ensure paths persist: create paths.json + paths.sh on first run
    ensurePathsPersisted();
    return { ...DEFAULT_PATHS };
  }
}

function ensurePathsPersisted() {
  try {
    const p = { ...DEFAULT_PATHS };
    fs.mkdirSync(path.dirname(PATHS_FILE), { recursive: true });
    fs.writeFileSync(PATHS_FILE, JSON.stringify(p, null, 2));
    const sh = [
      '# Auto-generated by dashboard — do not edit manually',
      `export WORKSPACE_DIR="${p.workspace}"`,
      `export PROJECT_ROOT="${p.projectRoot}"`,
    ].join('\n') + '\n';
    fs.writeFileSync(path.join(SHARED_DIR, 'paths.sh'), sh);
  } catch {}
}

function savePaths(updates) {
  const current = loadPaths();
  const next = { ...current, ...updates };

  // Resolve ~ to home dir
  for (const k of ['workspace', 'projectRoot']) {
    if (next[k] && next[k].startsWith('~')) {
      next[k] = path.join(process.env.HOME || '~', next[k].slice(1));
    }
    next[k] = path.resolve(next[k]);
  }

  fs.mkdirSync(path.dirname(PATHS_FILE), { recursive: true });
  fs.writeFileSync(PATHS_FILE, JSON.stringify(next, null, 2));

  // Also write shared/paths.sh so agent scripts can source it
  const sh = [
    '# Auto-generated by dashboard — do not edit manually',
    `export WORKSPACE_DIR="${next.workspace}"`,
    `export PROJECT_ROOT="${next.projectRoot}"`,
  ].join('\n') + '\n';
  fs.writeFileSync(path.join(SHARED_DIR, 'paths.sh'), sh);

  return next;
}

// ── Helpers ──────────────────────────────────────────────────

function parseConfig() {
  try {
    const content = fs.readFileSync(CONFIG_FILE, 'utf8');
    const cfg = {};
    const re  = /^(AI_\w+)="(\w+)"/gm;
    let m;
    while ((m = re.exec(content)) !== null) cfg[m[1]] = m[2];
    return cfg;
  } catch { return {}; }
}

// Allowed AI values (prevents shell injection)
const ALLOWED_AI_VALUES = ['claude', 'gemini', 'cursor'];
const ALLOWED_CONFIG_KEYS = ['AI_PO', 'AI_TECH', 'AI_DEV', 'AI_QA', 'AI_DEVOPS'];

function updateConfig(updates) {
  for (const [k, v] of Object.entries(updates)) {
    if (!ALLOWED_CONFIG_KEYS.includes(k))
      throw new Error(`Invalid config key: ${k}`);
    const val = String(v).toLowerCase().trim();
    if (!ALLOWED_AI_VALUES.includes(val))
      throw new Error(`Invalid AI value for ${k}: must be one of ${ALLOWED_AI_VALUES.join(', ')}`);
  }
  let content = fs.readFileSync(CONFIG_FILE, 'utf8');
  for (const [k, v] of Object.entries(updates)) {
    const val = String(v).toLowerCase().trim();
    content = content.replace(
      new RegExp(`^(${k}=")[^"]*(".*$)`, 'm'),
      `$1${val}$2`
    );
  }
  fs.writeFileSync(CONFIG_FILE, content);
}

function getInboxCounts() {
  const roles = ['po', 'tech', 'dev', 'qa', 'devops'];
  return Object.fromEntries(roles.map(r => {
    try {
      const n = fs.readdirSync(path.join(INBOX_DIR, r))
                  .filter(f => f.endsWith('.task')).length;
      return [r, n];
    } catch { return [r, 0]; }
  }));
}

function checkTmux() {
  try { execSync('tmux has-session -t ai_team 2>/dev/null'); return true; }
  catch { return false; }
}

function sendTask(role, sender, task, opts = {}) {
  const dir = path.join(INBOX_DIR, role);
  fs.mkdirSync(dir, { recursive: true });
  const id = opts.taskId || Date.now();
  const lines = [`FROM: ${sender}`, `TIME: ${new Date().toISOString()}`, `TASK: ${task}`];
  if (opts.workflowId) lines.push(`WORKFLOW_ID: ${opts.workflowId}`);
  if (opts.handoffTo) lines.push(`HANDOFF_TO: ${opts.handoffTo}`);
  const file = path.join(dir, `${id}.task`);
  fs.writeFileSync(file, lines.join('\n') + '\n');
  return id;
}

function loadTasks() {
  try {
    const raw = fs.readFileSync(TASKS_FILE, 'utf8');
    return JSON.parse(raw);
  } catch { return []; }
}

function saveTask(task) {
  const tasks = loadTasks();
  tasks.unshift(task);
  const trimmed = tasks.slice(0, 50);
  fs.mkdirSync(path.dirname(TASKS_FILE), { recursive: true });
  fs.writeFileSync(TASKS_FILE, JSON.stringify(trimmed, null, 2));
}

function getTaskStatus(role, taskId) {
  const taskFile = path.join(INBOX_DIR, role, `${taskId}.task`);
  const doneFile = path.join(INBOX_DIR, role, `${taskId}.done`);
  if (fs.existsSync(taskFile)) return 'queued';
  if (fs.existsSync(doneFile)) return 'done';
  return 'done';
}

// Detect agents actively working: .done file modified within last 2 min
function getActiveAgents() {
  const roles = ['po', 'tech', 'dev', 'qa', 'devops'];
  const now = Date.now();
  const WINDOW_MS = 120_000;
  return Object.fromEntries(roles.map(r => {
    try {
      const dir = path.join(INBOX_DIR, r);
      const active = fs.readdirSync(dir)
        .filter(f => f.endsWith('.done'))
        .some(f => now - fs.statSync(path.join(dir, f)).mtimeMs < WINDOW_MS);
      return [r, active];
    } catch { return [r, false]; }
  }));
}

function buildFileTree(dir, base = '') {
  const items = [];
  try {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const rel = base ? `${base}/${e.name}` : e.name;
      if (e.isDirectory()) {
        items.push({ name: e.name, path: rel, type: 'dir',
                     children: buildFileTree(path.join(dir, e.name), rel) });
      } else {
        const { size } = fs.statSync(path.join(dir, e.name));
        items.push({ name: e.name, path: rel, type: 'file', size });
      }
    }
  } catch {}
  return items;
}

function dirExists(p) {
  try { return fs.statSync(p).isDirectory(); }
  catch { return false; }
}

// ── Middleware ────────────────────────────────────────────────

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ── Routes ────────────────────────────────────────────────────

app.get('/api/status', (_req, res) => {
  res.json({
    config: parseConfig(),
    inbox:  getInboxCounts(),
    tmux:   checkTmux(),
    paths:  loadPaths(),
    active: getActiveAgents(),
  });
});

app.get('/api/logs', (_req, res) => {
  try {
    const lines = fs.readFileSync(path.join(LOGS_DIR, 'team.log'), 'utf8')
                    .split('\n').filter(Boolean).slice(-100);
    res.json({ lines });
  } catch { res.json({ lines: [] }); }
});

// SSE — live log stream + heartbeat
app.get('/api/logs/stream', (req, res) => {
  res.setHeader('Content-Type',                'text/event-stream');
  res.setHeader('Cache-Control',               'no-cache');
  res.setHeader('Connection',                  'keep-alive');
  res.setHeader('Access-Control-Allow-Origin', '*');

  const logFile = path.join(LOGS_DIR, 'team.log');
  let lastSize = 0;

  try {
    const content = fs.readFileSync(logFile, 'utf8');
    lastSize = Buffer.byteLength(content, 'utf8');
    content.split('\n').filter(Boolean).slice(-25)
           .forEach(l => res.write(`data: ${JSON.stringify({ line: l, seed: true })}\n\n`));
  } catch {}
  const seedTasks = loadTasks().map(t => ({
    ...t,
    status: getTaskStatus((t.targets || [t.role])[0], t.id),
  }));
  const workflow = { ...loadWorkflowState(), reviewQueue: getReviewQueue() };
  res.write(`data: ${JSON.stringify({ tasks: seedTasks, workflow, seed: true })}\n\n`);

  const tick = setInterval(() => {
    try {
      const stat = fs.statSync(logFile);
      if (stat.size > lastSize) {
        const fd  = fs.openSync(logFile, 'r');
        const buf = Buffer.alloc(stat.size - lastSize);
        fs.readSync(fd, buf, 0, buf.length, lastSize);
        fs.closeSync(fd);
        lastSize = stat.size;
        buf.toString().split('\n').filter(Boolean)
           .forEach(l => res.write(`data: ${JSON.stringify({ line: l })}\n\n`));
      }
    } catch {}
    const tasks = loadTasks().map(t => ({
      ...t,
      status: getTaskStatus((t.targets || [t.role])[0], t.id),
    }));
    const workflow = { ...loadWorkflowState(), reviewQueue: getReviewQueue() };
    res.write(`data: ${JSON.stringify({ inbox: getInboxCounts(), tmux: checkTmux(), tasks, workflow, active: getActiveAgents() })}\n\n`);
  }, 1500);

  req.on('close', () => clearInterval(tick));
});

app.post('/api/task', (req, res) => {
  const { role, task, sender = 'Dashboard' } = req.body;
  if (!role || !task) return res.status(400).json({ error: 'Missing role or task' });

  const targets = role === 'all' ? ['po', 'tech', 'dev', 'qa', 'devops'] : [role];
  const taskIds = targets.map(r => sendTask(r, sender, task));

  const ts  = new Date().toISOString().replace('T', ' ').slice(0, 19);
  try { fs.appendFileSync(path.join(LOGS_DIR, 'team.log'),
        `[${ts}] [Dashboard] → ${role.toUpperCase()}: ${task}\n`); } catch {}

  const taskRecord = {
    id: taskIds[0],
    role, task, sender,
    targets,
    status: 'queued',
    createdAt: new Date().toISOString(),
  };
  saveTask(taskRecord);

  res.json({ success: true, routed: targets, taskId: taskIds[0] });
});

app.get('/api/tasks', (_req, res) => {
  const tasks = loadTasks();
  const enriched = tasks.map(t => {
    const role = t.targets?.[0] || t.role;
    return { ...t, status: getTaskStatus(role, t.id) };
  });
  res.json({ tasks: enriched });
});

// ── Skills API ───────────────────────────────────────────────
const SKILLS_FILE = path.join(SHARED_DIR, 'skills.json');

const SKILLS_CATALOG = [
  // API & Architecture
  { id: 'api-patterns',          name: 'API Patterns',           category: 'api',     description: 'REST/GraphQL API design patterns' },
  { id: 'architecture',          name: 'Architecture',           category: 'api',     description: 'System architecture design' },
  { id: 'intelligent-routing',   name: 'Intelligent Routing',    category: 'api',     description: 'Smart request routing strategies' },
  // Development Frameworks
  { id: 'app-builder',           name: 'App Builder',            category: 'dev',     description: 'Full application scaffolding' },
  { id: 'nextjs-react-expert',   name: 'Next.js / React',        category: 'dev',     description: 'Next.js and React expertise' },
  { id: 'nodejs-best-practices', name: 'Node.js Best Practices', category: 'dev',     description: 'Node.js patterns and practices' },
  { id: 'mcp-builder',           name: 'MCP Builder',            category: 'dev',     description: 'Model Context Protocol tools' },
  // Languages & Platforms
  { id: 'bash-linux',            name: 'Bash / Linux',           category: 'lang',    description: 'Shell scripting and Linux admin' },
  { id: 'powershell-windows',    name: 'PowerShell',             category: 'lang',    description: 'Windows automation' },
  { id: 'python-patterns',       name: 'Python Patterns',        category: 'lang',    description: 'Python best practices' },
  { id: 'rust-pro',              name: 'Rust Pro',               category: 'lang',    description: 'Systems programming in Rust' },
  // Design & Frontend
  { id: 'frontend-design',       name: 'Frontend Design',        category: 'design',  description: 'UI/UX design principles' },
  { id: 'mobile-design',         name: 'Mobile Design',          category: 'design',  description: 'Mobile-first design patterns' },
  { id: 'tailwind-patterns',     name: 'Tailwind Patterns',      category: 'design',  description: 'Tailwind CSS utility patterns' },
  { id: 'web-design-guidelines', name: 'Web Design Guidelines',  category: 'design',  description: 'Web standards and accessibility' },
  // Testing & Quality
  { id: 'testing-patterns',      name: 'Testing Patterns',       category: 'test',    description: 'Automated testing strategies' },
  { id: 'tdd-workflow',          name: 'TDD Workflow',           category: 'test',    description: 'Test-driven development' },
  { id: 'code-review-checklist', name: 'Code Review',            category: 'test',    description: 'Systematic code review' },
  { id: 'lint-and-validate',     name: 'Lint & Validate',        category: 'test',    description: 'Code quality tools' },
  { id: 'webapp-testing',        name: 'Webapp Testing',         category: 'test',    description: 'End-to-end web testing' },
  // Operations & Deployment
  { id: 'deployment-procedures', name: 'Deployment',             category: 'ops',     description: 'CI/CD and deployment workflows' },
  { id: 'server-management',     name: 'Server Management',      category: 'ops',     description: 'Infrastructure management' },
  { id: 'performance-profiling', name: 'Performance Profiling',  category: 'ops',     description: 'App performance analysis' },
  // Specialized Skills
  { id: 'database-design',       name: 'Database Design',        category: 'special', description: 'DB schema and query optimization' },
  { id: 'game-development',      name: 'Game Development',       category: 'special', description: 'Game mechanics and engines' },
  { id: 'geo-fundamentals',      name: 'Geo Fundamentals',       category: 'special', description: 'Geographic data and mapping' },
  { id: 'i18n-localization',     name: 'i18n / L10n',            category: 'special', description: 'Internationalization support' },
  { id: 'brainstorming',         name: 'Brainstorming',          category: 'special', description: 'Creative ideation techniques' },
  { id: 'behavioral-modes',      name: 'Behavioral Modes',       category: 'special', description: 'Context-aware behavior switching' },
  { id: 'clean-code',            name: 'Clean Code',             category: 'special', description: 'SOLID principles and patterns' },
  { id: 'documentation-templates', name: 'Documentation',        category: 'special', description: 'Docs templates and standards' },
  { id: 'plan-writing',          name: 'Plan Writing',           category: 'special', description: 'Technical planning documents' },
  { id: 'red-team-tactics',      name: 'Red Team Tactics',       category: 'special', description: 'Security testing strategies' },
  { id: 'seo-fundamentals',      name: 'SEO Fundamentals',       category: 'special', description: 'Search engine optimization' },
  { id: 'systematic-debugging',  name: 'Systematic Debugging',   category: 'special', description: 'Bug investigation methodology' },
  { id: 'vulnerability-scanner', name: 'Vulnerability Scanner',  category: 'special', description: 'Security vulnerability detection' },
  { id: 'parallel-agents',       name: 'Parallel Agents',        category: 'special', description: 'Multi-agent coordination' },
];

function loadAgentSkills() {
  try { return JSON.parse(fs.readFileSync(SKILLS_FILE, 'utf8')); }
  catch { return { po: [], tech: [], dev: [], qa: [], devops: [] }; }
}

function saveAgentSkills(skills) {
  fs.mkdirSync(path.dirname(SKILLS_FILE), { recursive: true });
  fs.writeFileSync(SKILLS_FILE, JSON.stringify(skills, null, 2));
}

const _VALID_SKILL_IDS = new Set(SKILLS_CATALOG.map(s => s.id));
const _VALID_AGENTS    = new Set(['po', 'tech', 'dev', 'qa', 'devops']);

app.get('/api/skills', (_req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.json({ skills: SKILLS_CATALOG });
});

app.get('/api/agent-skills', (_req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.json(loadAgentSkills());
});

app.post('/api/agent-skills', (req, res) => {
  const { agent, skillId, action } = req.body;
  if (!agent || !skillId || !action)
    return res.status(400).json({ error: 'Missing agent, skillId, or action' });
  if (!_VALID_AGENTS.has(agent))
    return res.status(400).json({ error: 'Invalid agent' });
  if (!_VALID_SKILL_IDS.has(skillId))
    return res.status(400).json({ error: 'Invalid skillId' });
  if (!['add', 'remove'].includes(action))
    return res.status(400).json({ error: 'action must be add or remove' });

  const skills = loadAgentSkills();
  if (!skills[agent]) skills[agent] = [];
  if (action === 'add' && !skills[agent].includes(skillId)) {
    skills[agent].push(skillId);
  } else if (action === 'remove') {
    skills[agent] = skills[agent].filter(s => s !== skillId);
  }
  saveAgentSkills(skills);
  res.json({ success: true, agentSkills: skills });
});

// ── Workflow API ─────────────────────────────────────────────
const WORKFLOW_STATE_FILE = path.join(SHARED_DIR, 'workflow_state.json');

function loadWorkflowState() {
  try {
    return JSON.parse(fs.readFileSync(WORKFLOW_STATE_FILE, 'utf8'));
  } catch { return { pipelines: [], current: null }; }
}

function saveWorkflowState(state) {
  fs.mkdirSync(path.dirname(WORKFLOW_STATE_FILE), { recursive: true });
  fs.writeFileSync(WORKFLOW_STATE_FILE, JSON.stringify(state, null, 2));
}

function parseHandoffFile(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const handoffTo = (content.match(/^HANDOFF_TO=(.+)$/m) || [])[1]?.trim();
    const taskMatch = content.match(/---TASK---\n([\s\S]*?)(?=\n---OUTPUT---|$)/);
    const outputMatch = content.match(/---OUTPUT---\n([\s\S]*)$/);
    return {
      handoffTo,
      task: taskMatch?.[1]?.trim() || '',
      output: outputMatch?.[1]?.trim() || '',
    };
  } catch { return null; }
}

function getReviewQueue() {
  const items = [];
  fs.mkdirSync(WORKFLOW_DIR, { recursive: true });
  try {
    for (const f of fs.readdirSync(WORKFLOW_DIR)) {
      if (!f.endsWith('.handoff')) continue;
      const full = path.join(WORKFLOW_DIR, f);
      const parsed = parseHandoffFile(full);
      if (!parsed) continue;
      const m = f.match(/^(\d+)_(po|tech)\.handoff$/);
      if (!m) continue;
      items.push({
        id: m[1],
        fromRole: m[2],
        handoffTo: parsed.handoffTo,
        task: parsed.task,
        output: parsed.output,
        filePath: full,
      });
    }
  } catch {}
  return items;
}

app.get('/api/workflow', (_req, res) => {
  const state = loadWorkflowState();
  const reviewQueue = getReviewQueue();
  res.json({ ...state, reviewQueue });
});

app.post('/api/workflow/start', (req, res) => {
  const { task } = req.body;
  if (!task) return res.status(400).json({ error: 'Missing task' });
  const workflowId = Date.now().toString();
  const state = loadWorkflowState();
  state.current = { id: workflowId, task, stage: 'po', createdAt: new Date().toISOString() };
  state.pipelines = state.pipelines || [];
  state.pipelines.unshift(state.current);
  state.pipelines = state.pipelines.slice(0, 20);
  saveWorkflowState(state);

  sendTask('po', 'Dashboard', task, { workflowId, handoffTo: 'tech', taskId: workflowId });
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
  try { fs.appendFileSync(path.join(LOGS_DIR, 'team.log'),
        `[${ts}] [Dashboard] → PO (workflow): ${task.slice(0, 80)}…\n`); } catch {}

  res.json({ success: true, workflowId });
});

const HANDOFF_CHAIN = { po: 'tech', tech: 'dev', dev: 'qa' };

app.post('/api/workflow/approve', (req, res) => {
  const { reviewId, fromRole, handoffTo, output } = req.body;
  if (!reviewId || !fromRole || !handoffTo) return res.status(400).json({ error: 'Missing fields' });

  const nextHandoff = HANDOFF_CHAIN[handoffTo] || null;
  const nextTask = `Based on ${fromRole === 'po' ? 'Product Owner requirements' : 'Tech Lead architecture'}:\n\n${output}\n\n---\n\nProceed with: ${handoffTo === 'tech' ? 'technical design' : handoffTo === 'dev' ? 'implementation' : 'testing'}.`;

  sendTask(handoffTo, 'Dashboard', nextTask, {
    workflowId: reviewId,
    handoffTo: nextHandoff,
    taskId: reviewId,
  });

  try {
    const handoffPath = path.join(WORKFLOW_DIR, `${reviewId}_${fromRole}.handoff`);
    if (fs.existsSync(handoffPath)) fs.unlinkSync(handoffPath);
  } catch {}

  // Update workflow state so pipeline shows next stage
  const wfState = loadWorkflowState();
  if (wfState.current && String(wfState.current.id) === String(reviewId)) {
    wfState.current.stage = handoffTo;
    saveWorkflowState(wfState);
  }

  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
  try { fs.appendFileSync(path.join(LOGS_DIR, 'team.log'),
        `[${ts}] [Dashboard] Approved ${fromRole} → ${handoffTo}\n`); } catch {}

  res.json({ success: true });
});

app.post('/api/workflow/reject', (req, res) => {
  const { reviewId, fromRole } = req.body;
  if (!reviewId || !fromRole) return res.status(400).json({ error: 'Missing fields' });
  try {
    const handoffPath = path.join(WORKFLOW_DIR, `${reviewId}_${fromRole}.handoff`);
    if (fs.existsSync(handoffPath)) fs.unlinkSync(handoffPath);
  } catch {}
  res.json({ success: true });
});

app.get('/api/config', (_req, res) => res.json(parseConfig()));

app.post('/api/config', (req, res) => {
  try {
    updateConfig(req.body);
    const config = parseConfig();
    res.json({ success: true, config });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// ── Paths API ────────────────────────────────────────────────

app.get('/api/paths', (_req, res) => {
  res.json({ ...loadPaths(), defaults: DEFAULT_PATHS });
});

app.post('/api/paths', (req, res) => {
  const { workspace, projectRoot } = req.body;
  if (!workspace && !projectRoot)
    return res.status(400).json({ error: 'Provide workspace and/or projectRoot' });
  try {
    const saved = savePaths({ workspace, projectRoot });
    for (const p of Object.values(saved)) fs.mkdirSync(p, { recursive: true });
    res.json({ success: true, paths: saved });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// ── Workspace (.code-workspace) API ──────────────────────────

// Parse VS Code's JSONC format (comments, trailing commas) safely
function parseJsonc(text) {
  const errors = [];
  const result = parse(text, errors, { allowTrailingComma: true });
  if (errors.length > 0) throw new Error(`JSONC parse error at offset ${errors[0].offset}`);
  return result;
}

function resolveFolder(folderPath, wsDir) {
  if (!folderPath) return null;
  const expanded = folderPath.startsWith('~')
    ? path.join(process.env.HOME || '', folderPath.slice(1))
    : folderPath;
  const abs = path.isAbsolute(expanded) ? expanded : path.resolve(wsDir, expanded);
  return { abs, exists: dirExists(abs) };
}

// Allowed base dirs for workspace parse (prevents arbitrary file read)
const ALLOWED_PARSE_BASE_DIRS = [
  process.env.HOME || '',
  TEAM_DIR,
  path.join(process.env.HOME || '', 'projects'),
  path.join(process.env.HOME || '', 'Projects'),
  path.join(process.env.HOME || '', 'project'),
].filter(Boolean);

function isPathAllowed(filePath) {
  const resolved = path.resolve(filePath);
  return ALLOWED_PARSE_BASE_DIRS.some(base => {
    const baseResolved = path.resolve(base);
    return resolved === baseResolved || resolved.startsWith(baseResolved + path.sep);
  });
}

// Load & parse a .code-workspace file from a server-side path
app.post('/api/workspace/parse', (req, res) => {
  const { filePath } = req.body;
  if (!filePath) return res.status(400).json({ error: 'Missing filePath' });

  const resolved = filePath.startsWith('~')
    ? path.join(process.env.HOME || '', filePath.slice(1))
    : path.resolve(filePath);

  if (!isPathAllowed(resolved))
    return res.status(403).json({ error: 'Path not allowed. Use HOME, TEAM_DIR, or ~/projects' });

  try {
    const content = fs.readFileSync(resolved, 'utf8');
    const ws      = parseJsonc(content);
    const wsDir   = path.dirname(resolved);
    const name    = ws.folders?.[0]?.name
                 || path.basename(resolved, '.code-workspace');

    const folders = (ws.folders || []).map((f, i) => {
      const r = resolveFolder(f.path, wsDir);
      return {
        index:        i,
        name:         f.name || (r ? path.basename(r.abs) : f.path),
        relativePath: f.path,
        absolutePath: r?.abs  || null,
        exists:       r?.exists || false,
      };
    });

    res.json({ success: true, name, filePath: resolved, folders });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

// Parse content sent from browser (FileReader) — relative paths stay relative
app.post('/api/workspace/parse-content', (req, res) => {
  const { content, name = 'workspace' } = req.body;
  if (!content) return res.status(400).json({ error: 'Missing content' });
  try {
    const ws      = parseJsonc(content);
    const folders = (ws.folders || []).map((f, i) => {
      const isAbs = path.isAbsolute(f.path);
      const abs   = isAbs ? f.path : null;
      return {
        index:        i,
        name:         f.name || path.basename(f.path) || f.path,
        relativePath: f.path,
        absolutePath: abs,
        exists:       abs ? dirExists(abs) : null,  // null = unknown
      };
    });
    res.json({ success: true, name, folders });
  } catch (e) {
    res.status(400).json({ error: `Parse error: ${e.message}` });
  }
});

// ── Browse API (folder picker) ───────────────────────────────
const ALLOWED_BROWSE_ROOTS = [
  '/',
  process.env.HOME || '',
  '/Users',
  '/home',
  path.join(process.env.HOME || '', 'projects'),
  path.join(process.env.HOME || '', 'Projects'),
  path.join(process.env.HOME || '', 'project'),
  TEAM_DIR,
].filter(Boolean);

function isBrowsePathAllowed(dirPath) {
  const resolved = path.resolve(dirPath);
  return ALLOWED_BROWSE_ROOTS.some(root => {
    const r = path.resolve(root);
    return resolved === r || resolved.startsWith(r + path.sep);
  });
}

app.get('/api/browse', (req, res) => {
  let dir = req.query.path || process.env.HOME || '/';
  if (dir.startsWith('~')) dir = path.join(process.env.HOME || '', dir.slice(1));
  dir = path.resolve(dir);

  if (!dirExists(dir))
    return res.json({ error: 'Path not found', path: dir, items: [] });
  if (!isBrowsePathAllowed(dir))
    return res.json({ error: 'Path not allowed', path: dir, items: [] });

  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const items = entries
      .filter(e => e.isDirectory() && !e.name.startsWith('.'))
      .map(e => ({ name: e.name, path: path.join(dir, e.name), type: 'dir' }))
      .sort((a, b) => a.name.localeCompare(b.name));
    res.json({ path: dir, items, parent: path.dirname(dir) });
  } catch (e) {
    res.status(500).json({ error: e.message, path: dir, items: [] });
  }
});

app.get('/api/browse/roots', (_req, res) => {
  const roots = ALLOWED_BROWSE_ROOTS.filter(p => dirExists(p));
  res.json({ roots: roots.map(p => ({ path: p, name: path.basename(p) || p })) });
});

// ── Files API (uses projectRoot from paths.json) ─────────────

app.get('/api/files', (_req, res) => {
  const { projectRoot } = loadPaths();
  if (!dirExists(projectRoot))
    return res.json({ error: 'Project root not found', path: projectRoot, items: [] });
  res.json({ path: projectRoot, items: buildFileTree(projectRoot) });
});

app.get('/api/files/*', (req, res) => {
  const { projectRoot } = loadPaths();
  const rel  = req.params[0];
  const full = path.resolve(projectRoot, rel);
  if (!full.startsWith(path.resolve(projectRoot)))
    return res.status(403).json({ error: 'Forbidden' });
  try {
    res.json({ content: fs.readFileSync(full, 'utf8'), path: rel });
  } catch { res.status(404).json({ error: 'Not found' }); }
});

// API 404 — return JSON so frontend never gets HTML
app.use('/api', (req, res) => {
  res.status(404).json({ error: 'API not found', path: req.path });
});

// ── Start ────────────────────────────────────────────────────

app.listen(PORT, () => {
  const p = loadPaths();
  console.log('\n  ╔═══════════════════════════════════════════════════╗');
  console.log('  ║   🤖  AI Product Team Dashboard                   ║');
  console.log(`  ║   http://localhost:${PORT}                           ║`);
  console.log('  ╠═══════════════════════════════════════════════════╣');
  console.log(`  ║   workspace   : ${p.workspace.slice(-40).padEnd(40)} ║`);
  console.log(`  ║   projectRoot : ${p.projectRoot.slice(-40).padEnd(40)} ║`);
  console.log('  ╚═══════════════════════════════════════════════════╝\n');
});
